# Generated by Django 5.2.10 on 2026-01-18 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile'),
    ]

    operations = [
    ]
